'use strict';
const nodes=scenario.nodes,materials=scenario.materials;
const files=Object.fromEntries(['M-02','M-03','M-04','M-05','M-06','M-07','M-08','M-09','M-10','M-11','M-12','M-13','M-14','M-15'].map(id=>[id,'materials/'+id+'.pdf']));
let index=0,lives=3,selected=null,correct=0,wrong=0,critical=[],hints=0,unlocked=new Set(),opened=new Set(),ended=false,introPhase=0,lastFocus=null;
const quiz=document.getElementById('quiz'),modal=document.getElementById('modal');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function resources(){const root=document.getElementById('resources');root.replaceChildren();for(const m of materials.filter(m=>files[m.id])){const available=unlocked.has(m.id),a=document.createElement(available?'a':'span');a.className='resource'+(available?(opened.has(m.id)?' done':''):' locked');a.innerHTML=`<span>${esc(m.id)} · ${esc(m.title)}</span><em aria-hidden="true">${available?(opened.has(m.id)?'✓':'↗'):'🔒'}</em>`;if(available){a.href=files[m.id];a.target='_blank';a.rel='noopener';a.onclick=()=>{opened.add(m.id);resources();};}root.append(a);}}
function show(title,message){lastFocus=document.activeElement;document.getElementById('dialogTitle').textContent=title;document.getElementById('dialogMessage').textContent=message;modal.hidden=false;document.getElementById('dismiss').focus();}
function hide(){modal.hidden=true;if(lastFocus?.isConnected)lastFocus.focus();else quiz.querySelector('.choice')?.focus();}
function render(){resources();if(introPhase===0){quiz.innerHTML='<div class="welcome"><div class="speech">Здравствуйте! Начнём расследование?</div><img class="intro-mascot" src="intro-officer.gif" alt="Анимированный полицейский наставник"><div class="welcome-foot"><button class="button" id="begin" type="button">ПРОДОЛЖИТЬ</button></div></div>';document.getElementById('begin').onclick=()=>{introPhase=2;render();};return;}if(ended){const score=Math.max(0,Math.round(correct/nodes.length*100-wrong*2-hints));quiz.innerHTML=`<div class="result"><div class="icon" aria-hidden="true">${lives?'🎓':'♡'}</div><span class="eyebrow">${lives?'Итог дела':'Попытка завершена'}</span><h1>${lives?'Расследование завершено':'Сердца закончились'}</h1><p>Верных решений: ${correct} из ${nodes.length}. Обычных и критических ошибок: ${wrong}. Обращений к начальнику: ${hints}. Учебный показатель: ${score}%.</p><button class="button" id="again">Пройти ещё раз</button><div class="audit"><strong>Разбор попытки</strong><ul><li>Критические ошибки: ${critical.length?critical.map(esc).join(', '):'нет'}.</li><li>Открыто обязательных документов: ${materials.filter(m=>m.required&&opened.has(m.id)).length} из ${materials.filter(m=>m.required&&files[m.id]).length}.</li></ul></div></div>`;document.getElementById('again').onclick=restart;return;}
const n=nodes[index];quiz.innerHTML=`<div class="line"><span class="eyebrow">Этап ${index+1} / ${nodes.length} · ${esc(n.id)}</span><span class="hearts" aria-label="Осталось сердец: ${lives}">${[0,1,2].map(i=>i<lives?'♥':'<i>♥</i>').join('')}</span></div><div class="bar" role="progressbar" aria-label="Прогресс" aria-valuenow="${index}" aria-valuemin="0" aria-valuemax="${nodes.length}"><span style="width:${index/nodes.length*100}%"></span></div><span class="eyebrow">${esc(n.title)}</span><h1>Ваше решение</h1><p class="situation">${esc(n.situation)}</p><div class="choice-list">${n.options.map((o,i)=>`<button type="button" class="choice ${selected===i?'selected':''}" data-choice="${i}"><span class="letter">${'АБВГ'[i]}</span><span>${esc(o.text)}</span></button>`).join('')}</div><div class="actions"><button class="button" id="check" ${selected===null?'disabled':''}>Принять решение</button><button class="button secondary" id="supervisor">Обратиться к начальнику</button></div><p class="info">${esc(n.basis||'')} · Источник: сценарий учебной игры</p>`;
quiz.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.choice);render();});document.getElementById('check').onclick=check;document.getElementById('supervisor').onclick=()=>{hints++;show('Подсказка начальника',n.hint||'Изучите доступные материалы и проверьте правовое основание решения.');};}
function check(){if(selected===null)return;const n=nodes[index],o=n.options[selected];selected=null;if(o.status==='Правильный'){correct++;for(const id of n.unlock)unlocked.add(id);if(n.id==='F-01'){const missing=materials.filter(m=>m.required&&files[m.id]&&!opened.has(m.id));if(missing.length){correct--;render();show('Проверьте материалы',`Откройте обязательные материалы: ${missing.map(m=>m.id).join(', ')}. Затем повторите финальное решение.`);return;}}index++;if(index===nodes.length)ended=true;render();show('Решение принято',o.feedback);return;}
wrong++;const isCritical=o.status==='Критическая ошибка';if(isCritical){lives--;critical.push(`${n.id}: ${o.text}`);}if(lives===0)ended=true;render();show(isCritical?'Критическая ошибка — потеряно сердце':'Попробуйте ещё раз',`${o.feedback}${lives===0?' Сердца закончились; откройте итог и начните новую попытку.':''}`);}
function restart(){index=0;lives=3;selected=null;correct=0;wrong=0;critical=[];hints=0;unlocked=new Set();opened=new Set();ended=false;introPhase=0;hide();render();}
document.getElementById('dismiss').onclick=hide;document.getElementById('restart').onclick=restart;document.addEventListener('keydown',e=>{if(!modal.hidden&&e.key==='Escape')hide();if(!modal.hidden&&e.key==='Tab'){e.preventDefault();document.getElementById('dismiss').focus();}});render();
