'use strict';
const nodes=scenario.nodes,materials=scenario.materials;
const files=Object.fromEntries(Array.from({length:14},(_,i)=>{const id=`M-${String(i+2).padStart(2,'0')}`;return [id,`materials/${id}.pdf`]}));
const tasks={
'M-02':'Проверьте, как описаны обстановка, изъятие объектов и упаковка.',
'M-03':'Отделите лично увиденное уборщиком от его предположений.',
'M-04':'Найдите источник сведений соседа и причину обращения в полицию.',
'M-05':'Проверьте дату, основание и предварительную квалификацию.',
'M-06':'Сравните показания уборщика с первоначальным объяснением.',
'M-07':'Установите, что иностранный свидетель видел лично и что узнал от других.',
'M-08':'Рассмотрите отпечаток и его масштабную фиксацию.',
'M-09':'Рассмотрите отпечатки пальцев и место их изъятия.',
'M-10':'Проверьте количество и индивидуальные признаки купюр.',
'M-11':'Найдите выводы эксперта по следу обуви.',
'M-12':'Найдите выводы эксперта по следам рук.',
'M-13':'Найдите выводы эксперта о подлинности денежных билетов.',
'M-14':'Проверьте фактическое время задержания и время составления протокола.',
'M-15':'Проверьте участие защитника и позицию подозреваемого.'
};
const shuffle=a=>{const result=[...a];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;};
function makeOrders(){const positions=shuffle(Array.from({length:nodes.length},(_,i)=>i%4));return nodes.map((n,k)=>{const correct=n.options.find(o=>o.status==='Правильный');const others=shuffle(n.options.filter(o=>o!==correct));const slot=positions[k]%n.options.length;const order=[...others];order.splice(slot,0,correct);return order;});}
let orders=makeOrders(),index=0,lives=3,selected=null,correct=0,wrong=0,critical=[],hints=0,unlocked=new Set(),opened=new Set(),pending=[],checked=new Set(),ended=false,introPhase=0,lastFocus=null;
const quiz=document.getElementById('quiz'),modal=document.getElementById('modal');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function resources(){const root=document.getElementById('resources');root.replaceChildren();for(const m of materials.filter(m=>files[m.id])){const available=unlocked.has(m.id),a=document.createElement(available?'a':'span');a.className='resource'+(available?(opened.has(m.id)?' done':''):' locked');a.innerHTML=`<span>${esc(m.id)} · ${esc(m.title)}</span><em aria-hidden="true">${available?(opened.has(m.id)?'✓':'↗'):'🔒'}</em>`;if(available){a.href=files[m.id];a.target='_blank';a.rel='noopener';a.onclick=()=>{opened.add(m.id);setTimeout(()=>{resources();if(pending.length)renderDocuments();},0);};}root.append(a);}}
function show(title,message){lastFocus=document.activeElement;document.getElementById('dialogTitle').textContent=title;document.getElementById('dialogMessage').textContent=message;modal.hidden=false;document.getElementById('dismiss').focus();}
function hide(){modal.hidden=true;if(lastFocus?.isConnected)lastFocus.focus();else quiz.querySelector('button')?.focus();}
function header(){return `<div class="line"><span class="eyebrow">Этап ${index+1} / ${nodes.length} · ${esc(nodes[index].id)}</span><span class="hearts" aria-label="Осталось сердец: ${lives}">${[0,1,2].map(i=>i<lives?'♥':'<i>♥</i>').join('')}</span></div><div class="bar" role="progressbar" aria-label="Прогресс" aria-valuenow="${index}" aria-valuemin="0" aria-valuemax="${nodes.length}"><span style="width:${index/nodes.length*100}%"></span></div>`;}
function renderDocuments(){resources();const relevant=pending.map(id=>materials.find(m=>m.id===id));const ready=pending.every(id=>opened.has(id)&&checked.has(id));quiz.innerHTML=header()+`<span class="eyebrow">Результат действия</span><h1>Изучите полученные материалы</h1><p class="situation">Документы открыты сразу после решения ${esc(nodes[index].id)}. Откройте каждый и выполните короткую проверку перед следующим этапом.</p><div class="document-list">${relevant.map(m=>`<section class="document-card"><strong>${esc(m.id)} · ${esc(m.title)}</strong><p>${esc(tasks[m.id])}</p><a class="document-open" href="${files[m.id]}" target="_blank" rel="noopener" data-open="${m.id}">Открыть PDF ↗</a><label class="review-check"><input type="checkbox" data-reviewed="${m.id}" ${checked.has(m.id)?'checked':''} ${opened.has(m.id)?'':'disabled'}> Я проверил(а) материал</label></section>`).join('')}</div><div class="actions"><button class="button" id="next" ${ready?'':'disabled'}>ПРОДОЛЖИТЬ</button></div>`;quiz.querySelectorAll('[data-open]').forEach(a=>a.onclick=()=>{opened.add(a.dataset.open);setTimeout(renderDocuments,0);});quiz.querySelectorAll('[data-reviewed]').forEach(input=>input.onchange=()=>{if(input.checked)checked.add(input.dataset.reviewed);else checked.delete(input.dataset.reviewed);renderDocuments();});document.getElementById('next').onclick=()=>{if(!pending.every(id=>opened.has(id)&&checked.has(id)))return;pending=[];advance();};}
function render(){resources();if(introPhase===0){quiz.innerHTML='<div class="welcome"><div class="speech">Здравствуйте! Начнём расследование?</div><img class="intro-mascot" src="officer-russian.png" alt="Иллюстрированный наставник в форме"><div class="welcome-foot"><button class="button" id="begin" type="button">ПРОДОЛЖИТЬ</button></div></div>';document.getElementById('begin').onclick=()=>{introPhase=1;render();};return;}if(introPhase===1){quiz.innerHTML='<span class="eyebrow">Видеопролог · учебная постановка</span><h1>Последняя комбинация</h1><p class="situation">Посмотрите вступление. Сведения из постановочного видео сами по себе не являются доказательствами.</p><video class="intro-video" controls playsinline preload="metadata" aria-label="Видеопролог расследования"><source src="intro-case.mp4" type="video/mp4">Видео недоступно в этом браузере.</video><div class="intro-actions"><button class="button" id="begin" type="button">К РАССЛЕДОВАНИЮ</button></div>';document.getElementById('begin').onclick=()=>{quiz.querySelector('video')?.pause();introPhase=2;render();};return;}if(ended){const score=Math.max(0,Math.round(correct/nodes.length*100-wrong*2-hints));quiz.innerHTML=`<div class="result"><div class="icon" aria-hidden="true">${lives?'🎓':'♡'}</div><span class="eyebrow">${lives?'Итог дела':'Попытка завершена'}</span><h1>${lives?'Расследование завершено':'Сердца закончились'}</h1><p>Верных решений: ${correct} из ${nodes.length}. Ошибок: ${wrong}. Обращений к начальнику: ${hints}. Учебный показатель: ${score}%.</p><button class="button" id="again">Пройти ещё раз</button><div class="audit"><strong>Разбор попытки</strong><ul><li>Критические ошибки: ${critical.length?critical.map(esc).join(', '):'нет'}.</li><li>Проверено документов: ${checked.size} из ${Object.keys(files).length}.</li></ul></div></div>`;document.getElementById('again').onclick=restart;return;}if(pending.length){renderDocuments();return;}
const n=nodes[index],options=orders[index];quiz.innerHTML=header()+`<span class="eyebrow">${esc(n.title)}</span><h1>Ваше решение</h1><p class="situation">${esc(n.situation)}</p>${n.id==='D-01'&&window.CALL_AUDIO_FILE?`<div class="call-audio"><strong>Сообщение в полицию (английский язык)</strong><audio controls preload="metadata" src="${esc(window.CALL_AUDIO_FILE)}"></audio></div>`:''}<div class="choice-list">${options.map((o,i)=>`<button type="button" class="choice ${selected===i?'selected':''}" data-choice="${i}"><span class="letter">${'АБВГ'[i]}</span><span>${esc(o.text)}</span></button>`).join('')}</div><div class="actions"><button class="button" id="check" ${selected===null?'disabled':''}>ПРИНЯТЬ РЕШЕНИЕ</button><button class="button secondary" id="supervisor">Обратиться к начальнику</button></div><p class="info">${esc(n.basis||'')} · Источник: сценарий учебной игры</p>`;
quiz.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.choice);render();});document.getElementById('check').onclick=check;document.getElementById('supervisor').onclick=()=>{hints++;show('Подсказка начальника',n.hint||'Изучите доступные материалы и проверьте основание решения.');};}
function advance(){index++;selected=null;if(index===nodes.length)ended=true;render();}
function check(){if(selected===null)return;const n=nodes[index],o=orders[index][selected];selected=null;if(o.status==='Правильный'){correct++;pending=n.unlock.filter(id=>files[id]);for(const id of pending)unlocked.add(id);if(pending.length){renderDocuments();show('Решение принято',`${o.feedback} Теперь изучите материал${pending.length>1?'ы':''} этого этапа.`);}else{advance();show('Решение принято',o.feedback);}return;}
wrong++;const isCritical=o.status==='Критическая ошибка';if(isCritical){lives--;critical.push(`${n.id}: ${o.text}`);}if(lives===0)ended=true;render();show(isCritical?'Критическая ошибка — потеряно сердце':'Попробуйте ещё раз',`${o.feedback}${lives===0?' Сердца закончились.':''}`);}
function restart(){orders=makeOrders();index=0;lives=3;selected=null;correct=0;wrong=0;critical=[];hints=0;unlocked=new Set();opened=new Set();pending=[];checked=new Set();ended=false;introPhase=0;hide();render();}
document.getElementById('dismiss').onclick=hide;document.getElementById('restart').onclick=restart;document.addEventListener('keydown',e=>{if(!modal.hidden&&e.key==='Escape')hide();if(!modal.hidden&&e.key==='Tab'){e.preventDefault();document.getElementById('dismiss').focus();}});render();
